apiVersion: apps/v1
kind: Deployment
metadata:
  name: <APP_NAME>
  namespace: nginx
  labels:
    tier: backend
spec:
  replicas: <APP_NUMBER>
  selector:
    matchLabels:
      app: <APP_NAME>
      tier: backend
  template:
    metadata:
      labels:
        app: <APP_NAME>
        tier: backend
    spec:
      volumes:
        - name: conf
          configMap:
            name: nginx-conf
      containers:
        - name: <APP_NAME>
          image: uhub.service.ucloud.cn/shyin/php:<BUILD_TAG>
          command:
            - /bin/sh
            - -c
            - mkdir -p /var/log/nginx/ && cat /usr/local/nginx/conf/nginx.conf && /usr/local/php/sbin/php-fpm && /usr/local/nginx/sbin/nginx -g 'daemon off;'
          volumeMounts:
            - name: conf
              mountPath: /nginxconf
      imagePullSecrets:
        - name: mysecret