apiVersion: apps/v1
kind: Deployment
metadata:
  name: <APP_NAME>
  namespace: nginx
  labels:
    tier: backend
spec:
  replicas: <APP_NUMBER>
  selector:
    matchLabels:
      app: <APP_NAME>
      tier: backend
  template:
    metadata:
      labels:
        app: <APP_NAME>
        tier: backend
    spec:
      volumes:
        - name: config
          configMap:
            name: nginx-config
            items:
              - key: config
                path: site.conf
        - name: conf
          configMap:
            name: nginx-conf
        - name: backend-conf
          configMap:
            name: backend-conf
        - name: backend-web
          configMap:
            name: backend-web
      containers:
        - name: <APP_NAME>
          image: uhub.service.ucloud.cn/shyin/php:<BUILD_TAG>
          command:
            - /bin/sh
            - -c
            - mkdir -p /var/log/nginx/ && ls nginxconf && mv /usr/local/nginx/conf/nginx.conf /usr/local/nginx/conf/nginx.conf_bak && cp nginxconf/nginx.conf /usr/local/nginx/conf/ && cat /usr/local/nginx/conf/nginx.conf && /usr/local/php/sbin/php-fpm && /usr/local/nginx/sbin/nginx -g 'daemon off;'
          volumeMounts:
            - name: config
              mountPath: /etc/nginx/conf.d
            - name: conf
              mountPath: /nginxconf
            - name: backend-web
              mountPath: /data/nginx/web
            - name: backend-conf
              mountPath: /data/nginx/back
      imagePullSecrets:
        - name: mysecret