apiVersion: apps/v1
kind: Deployment
metadata:
  name: php
  namespace: nginx
  labels:
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: php
      tier: backend
  template:
    metadata:
      labels:
        app: php
        tier: backend
    spec:
      volumes:
        - name: code
          persistentVolumeClaim:
            claimName: php-pvc-claim
      containers:
        - name: php
          image: uhub.service.ucloud.cn/shyin/php:<BUILD_TAG>
          volumeMounts:
            - name: code
              mountPath: /code
      initContainers:
        - name: install
          image: busybox
          volumeMounts:
            - name: code
              mountPath: /code
          command:
            - mv
            - "/data/app"
            - "/code"