apiVersion: apps/v1
kind: Deployment
metadata:
  name: <APP_NAME>
  namespace: nginx
  labels:
    app: <APP_NAME>
spec:
  replicas: <APP_NUMBER>
  selector:
    matchLabels:
      app: <APP_NAME>
  template:
    metadata:
      labels:
        app: <APP_NAME>
        version: <BUILD_TAG>
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: area
                    operator: In
                    values:
                      - <AREA>
      containers:
        - name: <APP_NAME>
          image: uhub.service.ucloud.cn/shyin/<APP_NAME>:<BUILD_TAG>
          volumeMounts:
            - name: shares
              mountPath: /data/shares
          command:
            - /bin/sh
            - -c
            - mkdir -p /var/log/nginx/ && cat /usr/local/nginx/conf/nginx.conf && /usr/local/php/sbin/php-fpm && /usr/local/nginx/sbin/nginx -g 'daemon off;'
      imagePullSecrets:
        - name: mysecret
      volumes:
        - name: shares
          persistentVolumeClaim:
            claimName: app-shares-pvc-claim