apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-k8s-cicd
  namespace: jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins-k8s-cicd
  template:
    metadata:
      labels:
        app: jenkins-k8s-cicd
    spec:
      containers:
        - image: uhub.ucloud.cn/shyin/jenkins_k8s_cicd:<BUILD_TAG>
          imagePullPolicy: IfNotPresent
          name: jenkins-k8s-cicd
      imagePullSecrets:
        - name: mysecret