apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-k8s-cicd
  namespace: jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins-k8s-cicd
  template:
    metadata:
      labels:
        app: jenkins-k8s-cicd
    spec:
      containers:
        - image: uhub.service.ucloud.cn/shyin/jenkins_k8s_cicd:<BUILD_TAG>
          imagePullPolicy: IfNotPresent
          name: jenkins-k8s-cicd
      imagePullSecrets:
        - name: mysecret

  ## kubectl create secret docker-registry mysecret --docker-server=uhub.service.ucloud.cn --docker-username=263230286@qq.com --docker-password=shyinwork -n jenkins