apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-app
  namespace: nginx
  labels:
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: php-app
      tier: backend
  template:
    metadata:
      labels:
        app: php-app
        tier: backend
    spec:
      volumes:
        - name: config
          configMap:
            name: nginx-config
            items:
              - key: config
                path: site.conf
        - name: conf
          configMap:
            name: nginx-conf
      containers:
        - name: php-app
          image: uhub.service.ucloud.cn/shyin/php-nginx:8
          command:
            - /bin/sh
            - -c
            - mkdir -p /var/log/nginx/ && ls nginxconf && mv /usr/local/nginx/conf/nginx.conf /usr/local/nginx/conf/nginx.conf_bak && cp nginxconf/nginx.conf /usr/local/nginx/conf/ && cat /usr/local/nginx/conf/nginx.conf && while true;do date;sleep 360000;done && /usr/local/nginx/sbin/nginx -g 'daemon off;'
          volumeMounts:
            - name: config
              mountPath: /etc/nginx/conf.d
            - name: conf
              mountPath: /nginxconf